### ISSUE TITLE
Empty visualization in rviz

### ISSUE THREAD

**Issue by quanvuong** [hmz-15/Interactive-Scene-Reconstruction#1]
Hi,

Thank you for the repo! 

I tried the visualization instruction in [interactive scene](https://github.com/hmz-15/Interactive-Scene-Reconstruction/tree/main/interactive_scene) but encountered an empty visualization window in rviz. Please see my screenshot for an illustration of the empty visualization window. Have you encountered this issue before and do you by any chance know how to fix it?

I used the reconstructed panoptic segments and estimated contact graph from the provided Google Drive link.

![Screenshot from 2021-11-23 15-07-29](https://user-images.githubusercontent.com/6988600/143143173-8ca72e41-ccd0-4f04-b2c2-a98922cd3db9.png)
Thank you!

**Comment by hmz-15** [comment]
Hi, thanks for your interests about our work! You need to generate Xacro following [2.1](https://github.com/hmz-15/Interactive-Scene-Reconstruction/tree/main/interactive_scene#21-xacro-scene-generation) before visualizing the scene in Rviz. Did you go through this step?

**Comment by quanvuong** [comment]
Hi!

Yes, I used the command in 2.1 to generate the Xacro file before running the visualization. Were you able to reproduce the issue by any chance?

**Comment by hmz-15** [comment]
Can you please show me the output of your xacro commands? Do you see "[OK] Done! `sceneNN_test` is saved at..." which indicates the success?

**Comment by quanvuong** [comment]
[xacro_command_output.txt](https://github.com/hmz-15/Interactive-Scene-Reconstruction/files/7591970/xacro_command_output.txt)

Yes, I saw the "[OK] Done!" message. Please find the complete output log in the file attached.

Please note that I change the scene name, but I made sure the changed name is consistent between the name of the folder inside `output`, the scene name passed to the generate xacro command and the scene name passed to the visualization command.

**Comment by hmz-15** [comment]
Thanks Quan. I think it may due to a typo in your command. It should be ":=" instead of ":==".

**Comment by quanvuong** [comment]
Can you please take another look? I had that typo in the image in my original post, but that returned an error and I fixed the typo in the second command (also in the same image) that was able to run and produce the empty visualization.

**Comment by TooSchoolForCool** [comment]
What is your system version? We need more information to debug you issue.

It seems the URDF file was parsed correctly, but TF information was not published as expected.

Could you please send us a copy of your generated xacro files? (The whole folder under <prefix>/scene_builder/output/<generated-scene>).

**Comment by quanvuong** [comment]
Please find the compressed file of output in the link below. Please note that I am using the scene name `sceneNN_test_from_google_drive` to run the visualization using the data provided by the Google link in [1.2](https://github.com/hmz-15/Interactive-Scene-Reconstruction/tree/main/interactive_scene#12-results-of-panoptic-mapping-and-cad-replacement)

Please find system info below:

Output of `uname -a: Linux telemaniu20 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

The output of running `dpkg -l | grep ros- > ros_packages_info.txt` is attached.
[ros_packages_info.txt](https://github.com/hmz-15/Interactive-Scene-Reconstruction/files/7592103/ros_packages_info.txt)

**Comment by quanvuong** [comment]
For the compressed output directory: https://drive.google.com/file/d/1dJi8Ulh9q6rPwAQIMHKqabG2mQ70wMtB/view?usp=sharing

**Comment by quanvuong** [comment]
btw, what is the ROS topics that the TF information is being published from? I can check it on my side. Thanks!

**Comment by TooSchoolForCool** [comment]
Please note that you cannot directly manually change the scene name (e.g., change the folder name in the scene_builder/output), as the xacro will use the original scene name to find dependent mesh files, xacro files. 

If you want to change the scene name, you should set the roslaunch file parameters while generating the scene. 

I browsed your `xacro_command_output.txt`, it seems you did not change the folder name by hand. The way you change the scene name is correct.

**Comment by TooSchoolForCool** [comment]
I tried your generated xacro scene `sceneNN_test_from_google_drive`. It works as expected on my side.

![scene_builder_rviz](https://user-images.githubusercontent.com/17400901/143158410-6e8fdbc7-7489-419e-bdac-55b5bca68510.png)

You can use command
```bash
rosrun rqt_graph rqt_graph
```
to check if ros node are launched as expected.

Here is an expected output

![scene_builder_rqt_graph](https://user-images.githubusercontent.com/17400901/143158495-ee0df6fb-a441-422c-813f-63d5447cac7c.png)

To check the TF information, you can use command
```bash
rosrun rqt_tf_tree rqt_tf_tree
```

and here is an example of expected output


![scene_builder_tf_tree](https://user-images.githubusercontent.com/17400901/143158546-898a54b6-001f-4b49-ab96-735f1183aca1.png)

**Comment by quanvuong** [comment]
Yes, for some reason the tf information is not being published. I include the output of `rosrun rqt_graph rqt_graph` and `rosrun rqt_tf_tree rqt_tf_tree` in the image below. 

Do you have any tips to debug this on my end?

![Screenshot from 2021-11-23 18-10-00](https://user-images.githubusercontent.com/6988600/143158809-5db8f336-e769-43d4-b723-8182454fa803.png)

**Comment by TooSchoolForCool** [comment]
Did you have `robot_state_publisher` and `joint_state_publisher` installed properly?

It seems your ROS environment misses some core modules.

**Comment by quanvuong** [comment]
What is your ros version? Checking the file `ros_packages_info.txt`, I can see that I had installed `ros-noetic-joint-state-publisher` and `ros-noetic-robot-state-publisher`, but the error still occurs.

**Comment by TooSchoolForCool** [comment]
> Yes, for some reason the tf information is not being published. I include the output of `rosrun rqt_graph rqt_graph` and `rosrun rqt_tf_tree rqt_tf_tree` in the image below.
> 
> Do you have any tips to debug this on my end?
> 
> ![Screenshot from 2021-11-23 18-10-00](https://user-images.githubusercontent.com/6988600/143158809-5db8f336-e769-43d4-b723-8182454fa803.png)

Another possible problem is that you did not close previously launched nodes. In your rqt_graph screenshot, it seems the  `robot_state_publisher` and `joint_state_publisher` are still running. You need to kill those running processes at backend.

**Comment by quanvuong** [comment]
I tried killing all ros nodes but still that doesn't fix the issue (please see attached image). Is there anyway I can run the visualization code in verbose mode to debug the issue?
![Screenshot from 2021-11-23 18-50-22](https://user-images.githubusercontent.com/6988600/143162796-47a02abb-26e2-4d0e-952f-a72526fe3ce7.png)

**Comment by hmz-15** [comment]
BTW, @quanvuong is there any chance that you run the gazebo command and get some error at some points? I remembered that I came across one similar case when I run gazebo failed, and then I just couldn't visualize the scene in rviz.

**Comment by TooSchoolForCool** [comment]
You can use `rostopic` to check if `TF` messages were published correctly.

BTW, I would recommend you to go through the [ROS URDF tutorial](http://wiki.ros.org/urdf/Tutorials) to check if those fundamental ROS modules work as expected.

**Comment by quanvuong** [comment]
I was able to fix the issue and visualize the scene in gazebo and rviz. Thank you for your quick reply and help!

**Comment by libaiwanovo** [comment]
Unfortunately I changed the place you described and it's still the same situation
