### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Nimingez** [hmz-15/Interactive-Scene-Reconstruction#11]
I just follow the readme
(robot-scene-recon) nmz@nmz-desktop:~/my_ws$ catkin build panoptic_mapping_pipeline map_proc scene_builder gazebo_simulation -j2
----------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/noetic
Workspace:                   /home/nmz/my_ws
----------------------------------------------------
Build Space:        [exists] /home/nmz/my_ws/build
Devel Space:        [exists] /home/nmz/my_ws/devel
Install Space:      [unused] /home/nmz/my_ws/install
Log Space:         [missing] /home/nmz/my_ws/logs
Source Space:       [exists] /home/nmz/my_ws/src
DESTDIR:            [unused] None
----------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
----------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        -j2
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
----------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
----------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
----------------------------------------------------
[build] Found 38 packages in 0.0 seconds.                                      
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
_______________________________________________________________________________
Errors     << catkin_tools_prebuild:cmake /home/nmz/my_ws/logs/catkin_tools_prebuild/build.cmake.000.log
CMake Error at /opt/ros/noetic/share/catkin/cmake/empy.cmake:30 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python3-empy'
Call Stack (most recent call first):
  /opt/ros/noetic/share/catkin/cmake/all.cmake:164 (include)
  /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)

cd /home/nmz/my_ws/build/catkin_tools_prebuild; catkin build --get-env catkin_tools_prebuild | catkin env -si  /usr/bin/cmake /home/nmz/my_ws/build/catkin_tools_prebuild --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/nmz/my_ws/devel/.private/catkin_tools_prebuild -DCMAKE_INSTALL_PREFIX=/home/nmz/my_ws/install; cd -

...............................................................................
Failed     << catkin_tools_prebuild:cmake              [ Exited with code 1 ]  
Failed    <<< catkin_tools_prebuild                    [ 1.0 seconds ]         
Abandoned <<< catkin_simple                            [ Unrelated job failed ]
Abandoned <<< eigen_catkin                             [ Unrelated job failed ]
Abandoned <<< approxmvbb_catkin                        [ Unrelated job failed ]
Abandoned <<< fcl                                      [ Unrelated job failed ]
Abandoned <<< gazebo_simulation                        [ Unrelated job failed ]
Abandoned <<< gflags_catkin                            [ Unrelated job failed ]
Abandoned <<< glog_catkin                              [ Unrelated job failed ]
Abandoned <<< eigen_checks                             [ Unrelated job failed ]
Abandoned <<< husky_description                        [ Unrelated job failed ]
Abandoned <<< husky_ur_description                     [ Unrelated job failed ]
Abandoned <<< libccd                                   [ Unrelated job failed ]
Abandoned <<< minkindr                                 [ Unrelated job failed ]
Abandoned <<< minkindr_conversions                     [ Unrelated job failed ]
Abandoned <<< orb_slam2_ros                            [ Unrelated job failed ]
Abandoned <<< panoptic_mapping_pipeline                [ Unrelated job failed ]
Abandoned <<< pcl_catkin                               [ Unrelated job failed ]
Abandoned <<< pcl_conversions                          [ Unrelated job failed ]
Abandoned <<< pcl_ros                                  [ Unrelated job failed ]
Abandoned <<< pg_map_ros                               [ Unrelated job failed ]
Abandoned <<< map_proc                                 [ Unrelated job failed ]
Abandoned <<< scene_builder                            [ Unrelated job failed ]
Abandoned <<< seg_msgs                                 [ Unrelated job failed ]
Abandoned <<< perception_ros                           [ Unrelated job failed ]
Abandoned <<< ur_description                           [ Unrelated job failed ]
Abandoned <<< ur_e_description                         [ Unrelated job failed ]
Abandoned <<< voxblox                                  [ Unrelated job failed ]
Abandoned <<< global_segment_map                       [ Unrelated job failed ]
Abandoned <<< voxblox_msgs                             [ Unrelated job failed ]
Abandoned <<< voxblox_rviz_plugin                      [ Unrelated job failed ]
Abandoned <<< voxblox_ros                              [ Unrelated job failed ]
Abandoned <<< vpp_msgs                                 [ Unrelated job failed ]
Abandoned <<< gsm_node                                 [ Unrelated job failed ]
[build] Summary: 0 of 33 packages succeeded.                                   
[build]   Ignored:   6 packages were skipped or are skiplisted.                
[build]   Warnings:  None.                                                     
[build]   Abandoned: 32 packages were abandoned.                               
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 1.0 seconds total.

**Comment by TooSchoolForCool** [comment]
Please carefully go through the error message before opening an issue here.

It already said in the error message:

> Unable to find either executable 'empy' or Python module 'em'... try installing the package 'python3-empy'

So just install the package, and build it again.

**Comment by Nimingez** [comment]
Thank you for your prompt response. I have already installed it. Do I just need to follow the install.md?

**Comment by hmz-15** [comment]
Yes, please just follow the instructions.
