### ISSUE TITLE
required python version couldnot be 3.7

### ISSUE THREAD

**Issue by wanglei-albert** [hmz-15/Interactive-Scene-Reconstruction#12]
python version:  3.7.16
ubuntu: 20.04
The code could be build as expected, however, an error of "cannot import name 'cached_property' from 'functools' " is thrown when I try to run the algorithm following the guideline.
After searching some blogs, I get to know that cached_property becomes available from python3.8. So it will be kind to update the installation guide and thanks.

**Comment by hmz-15** [comment]
Thanks for pointing this out! Just updated the version.
