### ISSUE TITLE
About real scene

### ISSUE THREAD

**Issue by libaiwanovo** [hmz-15/Interactive-Scene-Reconstruction#14]
Thank you for your wonderful work, I am using this project to test real scenarios, but why is it reversed when visualising CAD?
![Screenshot from 2024-07-16 20-06-27](https://github.com/user-attachments/assets/2d1f2a32-4ca0-4957-9a8c-a3c42c735e87)
Here's the scene I typed.
![Screenshot from 2024-07-16 20-08-57](https://github.com/user-attachments/assets/d0f58416-d1e1-4ef9-958d-67b51ed67d78)
This is the output CAD

The camera I use is a realsense d435i, looking forward to your answer！thank you

**Comment by hmz-15** [comment]
The CAD replacement algrithm assumes the world frame locates on the floor with one axis (you can specify it) pointing up. Please transform the scan w.r.t. a proper world frame first.

**Comment by libaiwanovo** [comment]
Can you be more specific? I don't really understand.

**Comment by hmz-15** [comment]
To make sure the CAD replacement works as expected, you need to transform the scene into a coordinate system with origin  on the ground and one of the axis (either x, y, or z) axis pointing up (opposite to the gravity direction). Then you will need to specify the `ground_axis` parameter in [this launch file](https://github.com/hmz-15/Interactive-Scene-Reconstruction/blob/main/cad_replacement/map_proc/launch/map_processing.launch), where 0 means x-up, 1 means y-up, and 2 means z-up. If you use our mapping system and follow [the instruction](https://github.com/hmz-15/Interactive-Scene-Reconstruction/blob/main/cad_replacement/map_proc/launch/map_processing.launch) to setup the SLAM coordinate, the reconstructed scene should be already represented in appropriate coordinate system.

**Comment by libaiwanovo** [comment]
Unfortunately I changed the place you described and it's still the same situation

**Comment by hmz-15** [comment]
Please try these two steps to debug: 1. visualize the 3D scan with coordinate system to make sure the coordinate system is aligned with the ground (origin on the ground, 2 axes align with the ground, and 1 axis points up). 2. check the semantic label of the ground - is it correctly segmented as "floor" or wrongly segmented as "wall"?

**Comment by libaiwanovo** [comment]
Thanks for your patience in answering, I'm trying to try
