### ISSUE TITLE
Error when catkin build panoptic_mapping_pipeline map_proc scene_builder gazebo_simulation -j2

### ISSUE THREAD

**Issue by Niamh5163** [hmz-15/Interactive-Scene-Reconstruction#16]
Hi, I'm having this problem when I'm doing this compilation step, I gather that it's a version issue with Eigen, but I don't know where and how to fix it.Can you help me? Thank you very much.
> 
Errors     << pcl_catkin:make /home/yjj/ros_ws/logs/pcl_catkin/build.make.001.log
......
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/voxel_grid.h:340:21: error: ‘Index’ is not a member of ‘Eigen’
  340 |         for (Eigen::Index ni = 0; ni < relative_coordinates.cols (); ni++)
      |                     ^~~~~
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/voxel_grid.h:340:35: error: ‘ni’ was not declared in this scope
  340 |         for (Eigen::Index ni = 0; ni < relative_coordinates.cols (); ni++)
      |                                   ^~
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/voxel_grid.h: In member function ‘std::vector<int> pcl::VoxelGrid<pcl::PCLPointCloud2>::getNeighborCentroidIndices(float, float, float, const MatrixXi&) const’:
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/voxel_grid.h:669:21: error: ‘Index’ is not a member of ‘Eigen’
  669 |         for (Eigen::Index ni = 0; ni < relative_coordinates.cols (); ni++)
      |                     ^~~~~
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/filters/include/pcl/filters/voxel_grid.h:669:35: error: ‘ni’ was not declared in this scope
  669 |         for (Eigen::Index ni = 0; ni < relative_coordinates.cols (); ni++)
      |                                   ^~
make[5]: *** [filters/CMakeFiles/pcl_filters.dir/build.make:232: filters/CMakeFiles/pcl_filters.dir/src/voxel_grid.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1176: filters/CMakeFiles/pcl_filters.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/pcl_src.dir/build.make:113: pcl_src-prefix/src/pcl_src-stamp/pcl_src-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:306: CMakeFiles/pcl_src.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
> 
I left out the big warning in the middle.

**Comment by Niamh5163** [comment]
When I run catkin clean and recompile in steps, I still get a similar problem：
> 
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle3d.hpp:278:15: error: ‘Index’ is not a member of ‘Eigen’
  278 |   for (Eigen::Index i = 0; i < coeff.size (); ++i)
      |               ^~~~~
/home/yjj/ros_ws/build/pcl_catkin/pcl_src-prefix/src/pcl_src/sample_consensus/include/pcl/sample_consensus/impl/sac_model_circle3d.hpp:278:28: error: ‘i’ was not declared in this scope
  278 |   for (Eigen::Index i = 0; i < coeff.size (); ++i)
      |                            ^
cc1plus: warning: ‘-Wabi’ won’t warn about anything [-Wabi]
cc1plus: note: ‘-Wabi’ warns about differences from the most up-to-date ABI, which is also used by default
cc1plus: note: use e.g. ‘-Wabi=11’ to warn about changes from GCC 7
make[5]: *** [sample_consensus/CMakeFiles/pcl_sample_consensus.dir/build.make:89: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/src/sac_model_circle3d.cpp.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1145: sample_consensus/CMakeFiles/pcl_sample_consensus.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
>

**Comment by hmz-15** [comment]
Looks like the error is due to the incompatibility between PCL and Eigen [see this link](https://github.com/PointCloudLibrary/pcl/issues/5381). We already provide the catkin version of both packages that should be compatible with each other [see here](https://github.com/hmz-15/voxblox-plusplus/blob/260c5bb87e7ca72519d08da78ecbddc653c39996/voxblox-plusplus_https.rosinstall) if you follow the installation instruction. One possibility is you have another Eigen installed globally (e.g., using apt-get). If this is the case, uninstalling the global Eigen will resolve the issue.

**Comment by Niamh5163** [comment]
Yes, it is the latter case! I found two eigen.pc files in my local environment pointing to different versions of eigen that I had installed in two ways. uninstalling and reinstalling eigen has fixed the problem, thank you very much!
