### ISSUE TITLE
ERROR: Service [/gsm_node/generate_mesh/] is not available.

### ISSUE THREAD

**Issue by DoctorXK** [hmz-15/Interactive-Scene-Reconstruction#3]
Hi dear author,

I finally build `panoptic_mapping_pipeline` successfully, but when I execute Step 4 `rosservice call /gsm_node/generate_mesh` in [Robust Panoptic Mapping](https://github.com/hmz-15/Interactive-Scene-Reconstruction/tree/main/mapping) I will encounter:
```
ERROR: Service [/gsm_node/generate_mesh/] is not available.
```
I cannot find `generate_mesh`  in my running environment and so as `rosservice call /gsm_node/extract_instances`.

When I reviewed the compilation process I found there was warning message when compiling gsm_node even though it didn't throw compilation ERROR.
```
Warnings << gsm_node:cmake /opt/ros/melodic/log/gsm_node/build.cmake.000.log 
CMake Warning at /opt/ros/melodic/devel/share/pcl catkin/cmake/pcl-extras.cmake:14 (find package): 
  By not providing "FindovTk.cmake" in cMAkE MODuLE PATH this project has asked CMake to find a package confiquration file provided by"QVTK"but CMake did not find one.
  Could not find a package configuration file provided by "QVTK" with any of
the following names: 
    QVTKConfig.cmake
    qvtk-config.cmake
  Add the installation prefix of "OVTK" to CMAKE PREFIX_PATH or set
  "OVTK DIR" to a directory containing one of the above files.If"OVTK 
  provides a separate development package or sokbe sure it has been 
  installed.
Call Stack (most recent call first):
  /opt/ros/melodic/devel/share/pclcatkin/cmake/pcl_catkinconfiq.cmake:222(include)
  /opt/ros/melodic/devel/share/globalsegment_map/cmake/globalsegment_mapConfig.cmake:197(find_package)
  /opt/ros/melodic/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package) 
  CMakeLists.txt:12(catkin simple)

cd /opt/ros/melodic/build/gsm_node; catkin build --det-env gsm_node catkin env -si /usr/bin/cmake /opt/ros/melodic/src/Interactive-Scene-Reconstruction/mappina/voxblox-plusplus/global_segment_map_node --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/opt/ros/melodic/devel -DCMAKE INSTALL PREFIX=/opt/ros/melodic/install -OCMAKE_CX X_STANDARD=14 -DCMAKE_BUILDTYPE=Release; cd -
```

Have you ever encounter this situation? Looking forward to your reply. : )

**Comment by hmz-15** [comment]
Hi there,

I think executing "source devel/setup.bash" in the terminal you want to call the services will solve the issue.

**Comment by DoctorXK** [comment]
Thanks for your reply : ) . 
Unfortunately it cannot work : ( . 
Actually there is no `generate_mesh` or `extract_instances` under the `/gsm_node` directory, and I cannot find them in my running environment using command `find / -name generate_mesh`. 
I guess the package `gsm_node` doesn't compile as espected even though it doesn't throw compilation ERROR. But I don't know how to check and fix it : ( .

**Comment by hmz-15** [comment]
Sorry for my later reply. `generate_mesh` and `extract_instances` are in fact two ros services implemented in `global_segment_map_node/src/controller.cpp`. You can explicitly compile `gsm_node` by:

```bash
catkin build gsm_node
```

You can check whether the service is available by:
```bash
rosservice list
```

**Comment by DoctorXK** [comment]
Sorry for my later reply.
I tried, but it seems not work. I cannot find `generate_mesh` and `extract_instances` under `rosservice list` after 
```
catkin build gsm_node
```
![1653213008(1)](https://user-images.githubusercontent.com/51693781/169689571-9cf013f5-2f03-4b30-b29a-4541d51a5058.jpg)
You can see there is some packages skipped or ignored.

After execute Step 4 you can see `Service [/gsm_node/generate_mesh] is not available.`
![1653213264](https://user-images.githubusercontent.com/51693781/169689755-5aafcca4-7f63-4865-b695-f3bec81f123b.jpg)

Another thing that hit me is when executing
```
roslaunch panoptic_mapping_pipeline scenenn_pano_mapping.launch sequence:=sceneNN_test
```
I can see some ERROR message about `gms_node:`
![1653213824(1)](https://user-images.githubusercontent.com/51693781/169690093-6a92561e-b018-4c18-8b76-d9811e7377f8.jpg)

**Comment by DoctorXK** [comment]
Another new ERROR occur!!! Lets forget about the previous discussion. :)

I try to install the running environment in a new machine with Ubuntu 20.04 and compile successfully. When I launch the ros nodes as [Step2](https://github.com/hmz-15/Interactive-Scene-Reconstruction/tree/main/mapping) in `Robust Panoptic Mapping`, the system prompts that the [gsm_node-4] process has died.
![1653319969(1)](https://user-images.githubusercontent.com/51693781/169855161-7ecc39d9-89cc-4673-a4ce-2837ada9d0ee.jpg)
But luckily it seems that the **panoptic mapping** is still running.
![image](https://user-images.githubusercontent.com/51693781/169855567-0276b901-8acb-4427-bb54-f96110911019.png)
When the mapping process ends, I call the two ros services to save results. But throw an **ERROR**
![1653320239(1)](https://user-images.githubusercontent.com/51693781/169855966-1fbd2ca1-9291-4084-bce1-bcdbd7e21290.jpg)
Is there any settings with respect to the cause of ERROR?

**Comment by TooSchoolForCool** [comment]
The `gsm_node` crashed and did not work as expected. 

As you can properly build (compile) the whole program without error message prompted, this must be a runtime error. 

I would suggest using `gdb` to debug this kind of error.  

Here is some of my conjecture: 
- We've test the whole program extensively, so I guess this runtime error might not be a segmentation fault or access violation.
-  One possibility is that something wrong with the 3rd party dependencies, e.g., vtk required by pcl.
- Besides, probably you linked the program to a wrong dynamic link library, for example, the program requires `lib.so.2.x.x`, but you link them to `lib.so.1.x.x`. This usually happened when you have multiple copies of same library, e.g., Boost, Eigen, OpenCV, etc.

**Comment by DoctorXK** [comment]
Thank you for your suggestions!!! :)

There is another thing I want to confirm with you, because I am afraid of missing potentially important information.
I notice that when the compilation complete the system will prompt that `Ignored:   6 packages were skipped or are skiplisted.`
![image](https://user-images.githubusercontent.com/51693781/169938767-7ea5db7c-ddaa-4330-a3f3-b08f2a08051c.png)


Do you think these packages ignoring will have a big impact with `gsm_node`?

**Comment by DoctorXK** [comment]
Hi there,

I have found out the reason why the `gsm_node` crashed. It was because I ran the `panoptic mapping` through MobaXterm and the visualization didn't work successfully through MobaXterm, which then caused the crash of `gsm_node`. As long as I run in local terminal and visualize in local screen, the `gsm_node` works normally. :)

Thanks for you help again~
