### ISSUE TITLE
How to save the CAD replacement results

### ISSUE THREAD

**Issue by DoctorXK** [hmz-15/Interactive-Scene-Reconstruction#4]
Hello,

The options in `map_proc/launch/map_processing.launch` doesn't seem to cover how to save the results of scene with CAD replacement. However, it seems that it is necesssary to save the CAD replacement results if we want these for post-processing. So I would like to ask how to save this kind of result? Or is there any saving options in the script?

It would be grateful if you can give some suggestions. Thank you very much!!!

**Comment by hmz-15** [comment]
The results will be saved under $Your_output_folder/contact_graph/ as a few json files. The output folder can be specified in the launch file. Hope this helps.

**Comment by DoctorXK** [comment]
Thanks for your quick reply!!!

The CAD replacement result here refers to the scene in visualization, which looks like a mesh data. I mean it there anyway to save the scene visualzation result?

**Comment by hmz-15** [comment]
Actually we didn’t represent the scene after CAD replacement as mesh. Instead we save the results the CAD replacement results as json files. To generate visualization, we load CAD models with specified scale and pose  (and mesh of layouts of course) into 3D viewers. You can do similar things if you want.

**Comment by DoctorXK** [comment]
Ok, I got it. Thanks again for your patient answering :)
