### ISSUE TITLE
Question about the ground truth localization

### ISSUE THREAD

**Issue by canglangzhige** [hmz-15/Interactive-Scene-Reconstruction#7]
In the tutorial "https://github.com/hmz-15/Interactive-Scene-Reconstruction/tree/main/mapping", Step 2, The ground truth pose of the sceneNN dataset is used, but the topic "ground truth pose" does not exit by the command "rosbag info scenenn_225.bag" :
![image](https://user-images.githubusercontent.com/48430568/179913535-877285e1-7d2a-47ed-9bbb-6f7620985b79.png)
How is the ground truth pose obtained, and how is it input into the entire system?

**Comment by hmz-15** [comment]
We read the camera pose from /tf transforms.
