### ISSUE TITLE
Something wrong when "catkin build map_proc"

### ISSUE THREAD

**Issue by acclwh** [hmz-15/Interactive-Scene-Reconstruction#8]
Hi,
When building the map_proc,there are some errors printed to log. I think the reason is googletest changed the tag to "main" instead of "master", could you please check the errors and modified the code?  or maybe I made a wrong build method? thanks.
the build log as following:
[ 10%] [34m[1mPerforming configure step for 'approxmvbb_src'[0m
-- Module path is now set to: /home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src/cmake/
-- Project name is: ApproxMVBB-
-- Set make program to /home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/parallelmake.sh
-- Meta: find meta
-- Meta: Setup External Projext
-- /home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/src/meta/include
-- Added '' to CMAKE_CXX and CMAKE_C_FLAGS:   and  
-- Adding  ApproxMVBB - Diameter ======================
-- ====================================================
-- Adding  ApproxMVBB - GeometryPredicates ============
-- Floating point control:
            HAVE__FPU_SETCW 
            HAVE_FPSETPREC 
            HAVE__CONTROLFP 
            HAVE__CONTROLFP_S 
            HAVE_FPU_INLINE_ASM_X86 1
-- ====================================================
-- ApproxMVBB: Write config file /home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/include/ApproxMVBB/Config/Config.hpp, 
-- ApproxMVBB Version: -- v2.1.1
 extracted from git tags!
-- Dependecy Libs (public): eigenLib
-- Downloading/updating googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download
make[3]: Entering directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[4]: Entering directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[5]: Entering directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[5]: Leaving directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[5]: Entering directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
[ 11%] Performing download step (git clone) for 'googletest-download'
Cloning into 'googletest-src'...
fatal: unable to access 'https://github.com/google/googletest.git/': GnuTLS recv error (-54): Error in the pull function.
Cloning into 'googletest-src'...
-- Had to git clone more than once:
          2 times.
fatal: invalid reference: master
CMake Error at googletest-download/googletest-download-prefix/tmp/googletest-download-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'

make[5]: Leaving directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[5]: *** [CMakeFiles/googletest-download.dir/build.make:91: googletest-download-prefix/src/googletest-download-stamp/googletest-download-download] Error 1
make[4]: Leaving directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[4]: *** [CMakeFiles/Makefile2:76: CMakeFiles/googletest-download.dir/all] Error 2
make[3]: Leaving directory '/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-download'
make[3]: *** [Makefile:84: all] Error 2
CMake Error at tests/CMakeLists.txt:14 (add_subdirectory):
  The source directory

    /home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/thirdparty/googletest-src

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/CMakeFiles/CMakeOutput.log".
See also "/home/lwh/ros-ws/build/approxmvbb_catkin/approxmvbb_src-prefix/src/approxmvbb_src-build/CMakeFiles/CMakeError.log".
make[2]: *** [CMakeFiles/approxmvbb_src.dir/build.make:108: approxmvbb_src-prefix/src/approxmvbb_src-stamp/approxmvbb_src-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:333: CMakeFiles/approxmvbb_src.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by hmz-15** [comment]
Hi there!
I tested the installation on Ubuntu 20.04 from scratch again, and there is no issue at my end.
Can you let me know what command you run to configure the dependency and build the package?

**Comment by acclwh** [comment]
I followed the guide of "Installation on Ubuntu". 

Prerequisites:
Python 3.7.13;
gcc version 9.4.0,g++ version 9.3.0;
opencv 4.2.0;

Clone the repository & install catkin dependencies: correct
Install python dependencies:correct

when building packages, use command as fellowing:
1.conda activate robot-scene-recon;
2.cd <your-ros-ws>;
3.catkin build panoptic_mapping_pipeline map_proc scene_builder gazebo_simulation -j2.

**Comment by hmz-15** [comment]
I tried the whole procedures from scratch, and everything worked well.
I also checked the googletest part, and looks like it actually checkout branch "main".

I think there might be a mismatch somewhere. Could you please double check if you are using the most up-to-date version of the repo, and follow every single step in the installation guide (including configure the workspace)? You probably need to clean-up the build files before you go over the steps again.

**Comment by hmz-15** [comment]
I know what the reason is. I guess you didn't update the dependency while getting a new version of the repo. Please try this in your ros workspace and run the build command again, and it should work:
```
sh src/Interactive-Scene-Reconstruction/wstool_setup_https.sh
```

**Comment by acclwh** [comment]
Thanks, I made mistake somewhere.
I deleted the dir and try again following the install guide. and then everything seems well.

**Comment by hmz-15** [comment]
Sounds good!
